import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {hierarchyEmbedding as embed,hierarchyDistance as dist,hierarchyComparison,HIERARCHY_MODEL} from '../public/hierarchy.js';import {makeEngine,GEOMETRIES,prefixDistance,tournament} from '../public/legacy-engine.js';import {sampleDataset} from '../public/data.js';import {fromReturns,generator} from '../scripts/relation-fixtures.mjs';
const rows=(r,n=30)=>fromReturns([Array.from({length:n-1},(_,i)=>typeof r==='function'?r(i):r)]).S0;
test('flat prices and missing volume have neutral states and a distinct coverage branch',()=>{const a=rows(0),b=structuredClone(a);b.forEach(r=>r.volume=0);const x=embed(a),y=embed(b);assert.deepEqual(x.summary.coarse,['quiet','neutral','neutral','neutral']);assert.equal(y.summary.volumeCoverage,0);assert.equal(hierarchyComparison(x,y).firstDifference,'volume');assert.equal(dist(x,x),0);assert.deepEqual(JSON.parse(JSON.stringify(x)),x);});
test('direction, volume and fine resolution survive legacy collisions',()=>{const x=embed(rows(.001)),y=embed(rows(.002));assert.ok(dist(x,y)>0);assert.deepEqual(x.prefix.slice(0,4),y.prefix.slice(0,4));assert.equal(embed(rows(-.002)).summary.coarse[1],'down');assert.equal(y.summary.coarse[1],'up');const c=rows(0);c.slice(15).forEach(r=>r.volume*=10);assert.equal(embed(c).summary.coarse[3],'expanding');c.slice(15).forEach(r=>r.volume=0);assert.equal(embed(c).summary.volumeCoverage,1);});
test('robust clipping controls isolated shocks without erasing persistent drift',()=>{const a=rows(i=>i%2?.003:-.003),b=structuredClone(a);b[15].close*=Math.exp(.5);b[15].high=Math.max(b[15].high,b[15].close);const x=embed(a),y=embed(b);assert.equal(x.summary.clippedReturns,0);assert.equal(y.summary.clippedReturns,2);assert.ok(y.summary.volatility<.02);assert.ok(Math.abs(y.summary.volatility-x.summary.volatility)<.005);assert.ok(embed(rows(.01)).summary.drift>.0099);});
test('price and volume units preserve leaves away from rounding boundaries',()=>{const rng=generator(7147);for(const n of [10,30,120])for(let k=0;k<25;k++){const a=rows(()=>.02*rng.normal(),n);a.forEach(r=>r.volume*=Math.exp(rng.normal()));const b=structuredClone(a);b.forEach(r=>{for(const key of ['open','high','low','close'])r[key]*=1e80;r.volume*=1e-70;});assert.deepEqual(embed(a).prefix,embed(b).prefix);}});
test('extreme finite prices, zero ranges and volumes remain finite',()=>{for(const n of [10,120]){const a=Array.from({length:n},(_,i)=>({open:i%2?1e300:1e-300,close:i%2?1e-300:1e300,high:1e300,low:1e-300,volume:i%3?1e300:0}));const x=embed(a);assert.ok(Object.values(x.summary).filter(v=>typeof v==='number').every(Number.isFinite));assert.equal(dist(x,x),0);assert.equal(embed(rows(0,n)).prefix.length,28);}});
test('invalid windows, sparse states, incompatible lengths and model variants reject',()=>{for(const a of [[],rows(0,9),rows(0,121),Array(10)])assert.throws(()=>embed(a));for(const k of ['open','high','low','close','volume']){const c=rows(0);c[1][k]=NaN;assert.throws(()=>embed(c));}const x=embed(rows(0));for(const y of [{...x,model:'other'},{...x,prefix:Array(28)},{...x,prefix:x.prefix.map((v,i)=>i===4?2:v)},{...x,n:31}])assert.throws(()=>dist(x,y));assert.throws(()=>makeEngine(sampleDataset(),'NVDA',{hierarchyModel:'bad'}));assert.throws(()=>prefixDistance([0],[0,1]));assert.throws(()=>prefixDistance(Array(4),[0,0,0,0]));});
test('strong triangle inequality on 20,000 adversarial prefixes and first difference',()=>{const rng=generator(947),arity=i=>i===0?4:i===3?9:i<4?3:2;const make=()=>({model:HIERARCHY_MODEL,n:30,prefix:Array.from({length:28},(_,i)=>Math.floor(rng.uniform()*arity(i)))});for(let k=0;k<20000;k++){const a=make(),b=structuredClone(a),c=structuredClone(a),ib=Math.floor(rng.uniform()*28),ic=Math.floor(rng.uniform()*28);b.prefix[ib]=(b.prefix[ib]+1)%arity(ib);c.prefix[ic]=(c.prefix[ic]+1)%arity(ic);assert.equal(dist(a,b),dist(b,a));assert.ok(dist(a,c)<=Math.max(dist(a,b),dist(b,c)));assert.equal(hierarchyComparison(a,b).sharedDepth,ib);assert.equal(dist(a,b),2**(-ib/4));}});
test('seven other representations and rankings exactly match v0.7',()=>{const ids=GEOMETRIES.filter(g=>g.id!=='ultrametric').map(g=>g.id),r=makeEngine(sampleDataset(),'NVDA',{relationEvidence:'legacy',signatureModel:'legacy'}).find(470,499,ids),a=JSON.parse(readFileSync(new URL('./v07-other-geometries.json',import.meta.url))),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');assert.equal(hash(r.rankings),a.rankings);for(const id of ids)assert.equal(hash(r.target[id]),a.targets[id]);});
test('future mutations cannot affect earlier hierarchy searches',()=>{const ds=sampleDataset(),r=makeEngine(ds,'NVDA').find(370,399,['ultrametric']),bad=structuredClone(ds);for(const s of Object.values(bad))for(const row of s.slice(400)){for(const k of ['open','high','low','close'])row[k]*=2;row.volume=0;}bad.AAPL[480].date='2099-01-01';assert.deepEqual(makeEngine(bad,'NVDA').find(370,399,['ultrametric']),r);assert.ok(r.rankings.ultrametric.every(c=>c.end+60<370));assert.equal(r.methodCandidateCount.ultrametric,r.candidateCount);});
test('walk-forward forecasts use strictly historical outcomes',async()=>{const ds=sampleDataset(),a=await tournament(makeEngine(ds,'NVDA'),['ultrametric']),bad=structuredClone(ds);for(const s of Object.values(bad))for(const row of s.slice(310)){for(const k of ['open','high','low','close'])row[k]*=2;row.volume*=10;}const b=await tournament(makeEngine(bad,'NVDA'),['ultrametric']);assert.ok(a[0].n);assert.equal(a[0].records[0].prediction,b[0].records[0].prediction);});

