import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/history.js';
const response=()=>({headers:{},status(n){this.code=n;return this;},json(d){this.data=d;return this;},setHeader(k,v){this.headers[k]=v;}});
async function mock(fn,run){const old=globalThis.fetch;globalThis.fetch=fn;try{await run();}finally{globalThis.fetch=old;}}
test('Test obtains the exact Stock dataset without a provider key',async()=>mock(async url=>{assert.equal(url.origin,'https://secondorder-stock-public.vercel.app');assert.equal(url.searchParams.get('years'),'3');assert.equal(url.searchParams.get('basket'),'1');assert.equal(url.searchParams.has('access_key'),false);return {ok:true,json:async()=>({source:'marketstack',dataset:{NVDA:[]},adjustment:'all'})};},async()=>{const r=response();await handler({query:{symbol:'NVDA'}},r);assert.equal(r.code,200);assert.equal(r.data.source,'marketstack');assert.equal(r.data.via,'stock.secondorder.tools');assert.match(r.headers['Cache-Control'],/s-maxage=21600/);}));
test('invalid parameters never contact Stock',async()=>mock(()=>{throw Error('must not fetch');},async()=>{for(const query of [{symbol:'evil/path'},{years:'2'},{basket:'yes'}]){const r=response();await handler({query},r);assert.equal(r.code,400);}}));
test('upstream quota failures preserve safe error details and are uncached',async()=>mock(async()=>({ok:false,status:429,json:async()=>({code:'provider-quota',error:'quota reached'})}),async()=>{const r=response();await handler({query:{}},r);assert.equal(r.code,429);assert.equal(r.data.code,'provider-quota');assert.equal(r.headers['Cache-Control'],'no-store');}));
test('unexpected sources and network failures never produce synthetic history',async()=>{for(const fn of [async()=>({ok:true,json:async()=>({source:'sample',dataset:{}})}),async()=>{throw Error('network');}])await mock(fn,async()=>{const r=response();await handler({query:{}},r);assert.equal(r.code,502);assert.equal(r.data.dataset,undefined);assert.equal(r.headers['Cache-Control'],'no-store');});});
