import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';
import {ripsPersistence,diagramW2,diagramSummary,topologyEmbedding,topologyDistance,TOPOLOGY_MODEL} from '../public/topology.js';
import {makeEngine,GEOMETRIES,tournament} from '../public/legacy-engine.js';import {sampleDataset} from '../public/data.js';import {generator,estimationFixture,fromReturns} from '../scripts/relation-fixtures.mjs';
const close=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<t,`${a} vs ${b}`),embed=ds=>topologyEmbedding(Object.values(ds),Object.keys(ds));
function brute(a,b){let best=Infinity;function walk(i,used,cost){if(i===a.length){for(let j=0;j<b.length;j++)if(!used.has(j))cost+=((b[j][1]-b[j][0])/2)**2;best=Math.min(best,cost);return;}walk(i+1,used,cost+((a[i][1]-a[i][0])/2)**2);for(let j=0;j<b.length;j++)if(!used.has(j)){used.add(j);walk(i+1,used,cost+Math.max(Math.abs(a[i][0]-b[j][0]),Math.abs(a[i][1]-b[j][1]))**2);used.delete(j);}}walk(0,new Set(),0);return Math.sqrt(best);}
test('known square Rips loop, triangle, duplicate vertices and permutation',()=>{
 const d=[[0,1,Math.SQRT2,1],[1,0,1,Math.SQRT2],[Math.SQRT2,1,0,1],[1,Math.SQRT2,1,0]],p=ripsPersistence(d);assert.equal(p[0].length,3);assert.deepEqual(p[1],[[1,Math.SQRT2]]);assert.deepEqual(ripsPersistence([[0,1,1],[1,0,1],[1,1,0]])[1],[]);assert.deepEqual(ripsPersistence([[0,0],[0,0]]),[[],[]]);const order=[2,0,3,1];assert.deepEqual(ripsPersistence(order.map(i=>order.map(j=>d[i][j]))),p);
});
test('positive features below old 1e-9 cutoff are retained',()=>{assert.deepEqual(ripsPersistence([[0,1e-10],[1e-10,0]])[0],[[0,1e-10]]);});
test('diagram matching handles deletion, unequal cardinality, diagonal points and collisions in summaries',()=>{
 close(diagramW2([[0,1]],[]),.5);close(diagramW2([[0,1],[0,1]],[]),Math.SQRT1_2);close(diagramW2([[0,0]],[]),0);const a=[[.125,.625]],b=[[.625,1.125]];assert.deepEqual(diagramSummary([a,[]]),diagramSummary([b,[]]));close(diagramW2(a,b),Math.sqrt(2)*.25);assert.ok(diagramW2(a,b)>0);
});
test('100 random small assignments match exhaustive partial matching',()=>{const rng=generator(731191),make=n=>Array.from({length:n},()=>{const b=rng.uniform();return [b,b+rng.uniform()];});for(let k=0;k<100;k++){const a=make(k%4),b=make(k*7%4);close(diagramW2(a,b),brute(a,b));}});
test('500 diagram triples satisfy metric properties, ordering and zero-diagonal invariance',()=>{const rng=generator(551991),make=()=>Array.from({length:Math.floor(rng.uniform()*8)},()=>{const b=rng.uniform();return [b,b+rng.uniform()];});for(let k=0;k<500;k++){const a=make(),b=make(),c=make(),d=diagramW2(a,b);close(d,diagramW2(b,a));close(diagramW2(a,a),0);close(d,diagramW2([...a].reverse(),b));close(d,diagramW2([...a,[.5,.5]],b));assert.ok(diagramW2(a,c)<=d+diagramW2(b,c)+1e-9);}});
test('invalid dissimilarities and nonfinite, sparse, reversed diagrams fail',()=>{
 for(const d of [[],Array(3),[[0,-1],[-1,0]],[[0,1],[.9,0]],[[0,Infinity],[Infinity,0]],[[1]]])assert.throws(()=>ripsPersistence(d));for(const a of [Array(2),[[0,Infinity]],[[.5,.2]],[[NaN,1]],[[0,3]]])assert.throws(()=>diagramW2(a,[]));
});
test('canonical windows, serialization, positive scaling and date-local checks',()=>{
 for(const p of [3,6,12])for(const n of [10,30,120]){const ds=estimationFixture(771+p+n,'factor',n,p).dataset,a=embed(ds);assert.equal(a.model,TOPOLOGY_MODEL);assert.equal(a.available,true);assert.deepEqual(JSON.parse(JSON.stringify(a)),a);const keys=Object.keys(ds).reverse();assert.deepEqual(topologyEmbedding(keys.map(s=>ds[s]),keys),a);close(topologyDistance(a,a),0);const rebased=structuredClone(ds);Object.values(rebased).forEach((rows,j)=>rows.forEach(r=>r.close*=2+j));close(topologyDistance(a,embed(rebased)),0,1e-6);}
});
test('constant assets are unavailable; duplicate nonconstant paths stay defined',()=>{
 const ds=estimationFixture(171,'factor').dataset;for(const r of ds.S0)r.close=100;assert.equal(embed(ds).available,false);assert.throws(()=>topologyDistance(embed(ds),embed(ds)));const returns=Array.from({length:29},(_,i)=>.01*Math.sin(i));const duplicate=fromReturns([returns,returns,returns]);assert.equal(embed(duplicate).available,true);
});
test('comparison requires same basket identity, length and variant',()=>{const a=embed(estimationFixture(717,'factor').dataset);assert.throws(()=>topologyDistance(a,{...a,n:31}));assert.throws(()=>topologyDistance(a,{...a,symbols:a.symbols.map(s=>'Z'+s)}));assert.throws(()=>topologyDistance(a,{...a,ablation:'linear-only'}));assert.throws(()=>topologyDistance(a,{...a,linear:Array(2)}));});
test('unlabelled topology deliberately loses asset rewiring; maximum supported diagram matching stays finite',()=>{const ds=estimationFixture(718,'factor').dataset,a=embed(ds),b=embed({...ds,S0:ds.S1,S1:ds.S0});close(topologyDistance(a,b),0,1e-7);const points=Array.from({length:66},(_,i)=>[i/100,1+i/100]);close(diagramW2(points,[]),Math.sqrt(66)*.5);close(diagramW2(points,[...points].reverse()),0);});
test('seven other geometries preserve v0.6 representations and ranks',()=>{const ids=GEOMETRIES.filter(g=>g.id!=='topology').map(g=>g.id),b=makeEngine(sampleDataset(),'NVDA',{relationEvidence:'legacy',hierarchyModel:'legacy',signatureModel:'legacy'}).find(470,499,ids),a=JSON.parse(readFileSync(new URL('./v06-other-geometries.json',import.meta.url))),hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex');assert.equal(hash(b.rankings),a.rankings);for(const id of ids)assert.equal(hash(b.target[id]),a.targets[id]);});
test('future prices and future date mismatch cannot change an earlier topology query',()=>{const ds=sampleDataset(),a=makeEngine(ds,'NVDA').find(370,399,['topology']),bad=structuredClone(ds);for(const rows of Object.values(bad))for(const r of rows.slice(400))for(const k of ['open','high','low','close'])r[k]*=2;bad.AAPL[480].date='2099-01-01';assert.deepEqual(makeEngine(bad,'NVDA').find(370,399,['topology']),a);assert.ok(a.rankings.topology.every(c=>c.end+60<370));});
test('undefined candidates are excluded and constant query does not vote',()=>{const ds=sampleDataset();for(const r of ds.NVDA.slice(0,100)){r.close=r.open=100;r.high=101;r.low=99;}const q=makeEngine(ds,'NVDA').find(470,499,['topology']);assert.ok(q.methodCandidateCount.topology<q.candidateCount);for(const r of ds.NVDA.slice(470))r.close=100;const t=makeEngine(ds,'AAPL').find(470,499,['topology','dtw']);assert.equal(t.target.topologyState.available,false);assert.deepEqual(t.active,['dtw']);});
test('past-only Lab and strict engine variant options',async()=>{const ds=sampleDataset(),a=await tournament(makeEngine(ds,'NVDA'),['topology']),bad=structuredClone(ds);for(const rows of Object.values(bad))for(const r of rows.slice(310))for(const k of ['open','high','low','close'])r[k]*=2;const b=await tournament(makeEngine(bad,'NVDA'),['topology']);assert.ok(a[0].n);assert.equal(a[0].records[0].prediction,b[0].records[0].prediction);assert.throws(()=>makeEngine(ds,'NVDA',{topologyModel:'bad'}));assert.throws(()=>makeEngine(ds,'NVDA',{topologyModel:'legacy',topologyAblation:'summary'}));});

